#!/bin/sh
# Free Software License
#   Author: Quyen Le Van <gaimande@gmail.com>

#############################
#   Entry point functuons   #
#############################

prefix_list="$prefix_list $DMROOT.Layer3Forwarding."
entry_execute_method_list="$entry_execute_method_list entry_execute_method_root_Layer3Forwarding"

entry_execute_method_root_Layer3Forwarding() {
    case "$1" in ""|"$DMROOT."|"$DMROOT.Layer3Forwarding."*)
        common_execute_method_obj "$DMROOT.Layer3Forwarding." "0"
		common_execute_method_param "$DMROOT.Layer3Forwarding.DefaultConnectionService" "0" "echo InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1" "" "" "1"

        return 0
        ;;
    esac
    return $E_INVALID_PARAMETER_NAME;
}

